### ISSUE TITLE
Counter separator in non-retina displays

### ISSUE THREAD

**Issue by sadovnik** [NikolayRys/Likely#125]
Counter separator is not visible in Google Chrome on non-retina displays:
![screen shot 2017-03-12 at 15 55 55](https://cloud.githubusercontent.com/assets/5960795/23831964/9024ecdc-073c-11e7-82ee-d173b92af53f.png)
![screen shot 2017-03-12 at 15 58 07](https://cloud.githubusercontent.com/assets/5960795/23831973/dd02a684-073c-11e7-8c5f-5df0c6ba9977.png)

Safari seems better:
![screen shot 2017-03-12 at 15 59 37](https://cloud.githubusercontent.com/assets/5960795/23831984/0abb56fc-073d-11e7-9d2d-2df7fd7d442b.png)
![screen shot 2017-03-12 at 16 00 57](https://cloud.githubusercontent.com/assets/5960795/23831986/22896ecc-073d-11e7-9dbb-129c9a6a283e.png)

Tested in OS X El Capitan.

**Comment by eugene-lazarev** [comment]
Seems like by-design feature. @ilyabirman, is it?

**Comment by ilyabirman** [comment]
I don’t think so. But probably we should remove this line altogether

**Comment by NikolayRys** [comment]
Line is removed
