### ISSUE TITLE
Add URL normalization

### ISSUE THREAD

**Issue by iamakulov** [NikolayRys/Likely#143]
There’re cases when people specify URLs that seem correct (e.g. `//google.com`) but can’t be understood by some social networks (e.g. Facebook). It would be great if Likely recognized such URLs and auto-corrected them.

I believe auto-correction should handle the following cases:
* An URL with `//` instead of a protocol: `//google.com` → `http://google.com`
* An URL without a protocol: `google.com` → `http://google.com`

PRs are welcome!

**Comment by NikolayRys** [comment]
I consider this to be an area user's responsibility.
