### ISSUE TITLE
Fix error in Chrome 49 (Latest for Windows XP)

### ISSUE THREAD

**Issue by ymatuhin** [NikolayRys/Likely#144]
Just check the support of Symbols and prevent this error.

![2017-12-19_13-11-11](https://user-images.githubusercontent.com/3757971/34152008-2bad0018-e4be-11e7-970b-0e08ba1b3163.png)

**Comment by NikolayRys** [comment]
this chrome is not latest for a very long time, so there is no value in supporting it
