### ISSUE TITLE
Is there any way to disable the counters?

### ISSUE THREAD

**Issue by deJong-IT** [NikolayRys/Likely#145]
Hi There,

Is there any way to disable the counters so it won't make the ajax calls?

I know you can override the counters using `data-counters="123"` or `data-counters="someurl"`, but I want to completely disable it so it doesn't show, and it doesn't try to do any ajax calls.
`data-counters="0"` doesn't work, it still is making the requests.

**Comment by iamakulov** [comment]
Please try `data-counters=""` (haven’t tested, but it should work).

Alternatively, you could initialize Likely [using the JS API](https://github.com/ilyabirman/Likely#using-as-a-commonjs-module) and pass `counters: false` as an option:

```js
likely.initiate({
  counters: false,
});
```

or

```js
likely.initiate(targetNode, {
  counters: false,
});
```

I’m keeping this open until we make disabling counters more straightforward.

**Comment by deJong-IT** [comment]
Thanks for your fast reply.

Unfortunately `data-counters=""` doesn't work. I'll see if I can use the API, at the moment I only used the `data-*` attributes as I didn't want to load an extra script just to initiate likely.

**Comment by iamakulov** [comment]
Are you setting `data-counters=""` on the `.likely` block? This worked in my setup: https://codepen.io/iamakulov/pen/VQvqem

(Try removing `data-counters` to see them.)

**Comment by deJong-IT** [comment]
I was setting it on the wrong block, changed it now and the counters are not visible, but even in your codepen, the ajax calls are still being made.

**Comment by iamakulov** [comment]
> but even in your codepen, the ajax calls are still being made.

Yep, that’s how it works right now...
Are these requests an issue for you? If yes, why?

**Comment by deJong-IT** [comment]
No, not really, it only makes the website a bit slower and I try to keep the requests to a minimum. And these are unnecessary because the results aren't used.

**Comment by iamakulov** [comment]
Got it! Iʼll take a look into disabling requests when counters are disabled, but no promises here.

Anyway, the requests should be sent only after the Likely script is loaded, and the page should be fully available at this moment. If you still experience rendering delays, you can try adding an `async` or `defer` attribute to the Likely `<script>` tag.

**Comment by optimist-law** [comment]
I fully support

**Comment by NikolayRys** [comment]
This will be included in the upcoming 2.5 which is being actively worked on.

**Comment by optimist-law** [comment]
Thanks for the feedback. Also, if you have the opportunity, pay attention to the indentation https://prnt.sc/qt3gmg. The top margin is slightly larger than the bottom. If there is an opportunity to align them and slightly reduce.

**Comment by NikolayRys** [comment]
Will be included in the upcoming release.
