### ISSUE TITLE
Facebook share counter does not show the number of shares

### ISSUE THREAD

**Issue by SvetikD** [NikolayRys/Likely#152]
I use the plugin on https://nuclearnews.io. 
It seems that after facebook has introduced some changes to Graph API on 30th of April the facebook share counter stopped showing the number of shares.

**Comment by dpetukhov** [comment]
We have the same problem on our site.

The solution I found most simple is change url according this post:

https://stackoverflow.com/questions/45613727/how-to-get-share-count-on-graph-api-2-10/45796935#45796935

Someone need to fix this and make a pull request. Maybe this one can be adopted https://github.com/ilyabirman/Likely/pull/153#pullrequestreview-238757359

**Comment by NikolayRys** [comment]
Will be fix in 2.4: #158
