### ISSUE TITLE
Add contributions guidelines

### ISSUE THREAD

**Issue by dzhlobo** [NikolayRys/Likely#17]
I think it would be good to clarify 
- who should update version of package, 
- should contributor build new release and add it to pull request or not,
- other things.

And GitHub suggests to add such information to CONTRIBUTING.md file.

**Comment by iamakulov** [comment]
Good point!

We want the Contributing guidelines to contain: 

* A guide to cloning, setting up and testing the project.
* A note that before submitting a PR with a new feature, it’d be great to open an issue. With it, we can discuss if we want the feature _before_ implementing it.
* A note that we update the release build and the version on our own.
* A code of conduct.

**Comment by iamakulov** [comment]
Added a new point:

> We want the Contributing guidelines to contain:
> - A guide into how to add a new button.

**Comment by NikolayRys** [comment]
Another point:
The repository is being maintained solely in English.

**Comment by NikolayRys** [comment]
They were added
