### ISSUE TITLE
Vertical margins slightly differ

### ISSUE THREAD

**Issue by vitkarpov** [NikolayRys/Likely#171]
Thanks for the feedback. Also, if you have the opportunity, pay attention to the indentation https://prnt.sc/qt3gmg. The top margin is slightly larger than the bottom. If there is an opportunity to align them and slightly reduce.

_Originally posted by @optimist-law in https://github.com/NikolayRys/Likely/issues/145#issuecomment-616089995_

**Comment by vitkarpov** [comment]
@optimist-law are you sure it's not on your website? I'm looking at https://ilyabirman.net/projects/likely/ and there are no margins at all (except negative ones to compensate buttons margins). If you could share your website address I'd take a look. Thanks.

**Comment by optimist-law** [comment]
An example can be seen here https://bit.ly/2RSzNFw

**Comment by vitkarpov** [comment]
I see, thanks. The problem is that styles on your page discard Likely's ones, it should've been negative margins there (as I wrote before to compensate buttons margins) but it's zero.

<img width="242" alt="Screen Shot 2020-04-19 at 1 50 29 PM" src="https://user-images.githubusercontent.com/3001791/79685894-c6a04280-8244-11ea-893b-cbecf6d666fc.png">

Do you think it makes sense to fix it on your side?

**Comment by NikolayRys** [comment]
@vitkarpov thanks for taking care of this 👍

**Comment by NikolayRys** [comment]
Hi, @optimist-law, I would appreciate it if you give us some feedback about what @vitkarpov has said.
Has it solved it?

**Comment by NikolayRys** [comment]
The reporter is unresponsive, closing the issue
