### ISSUE TITLE
Proofread and clean up the readme

### ISSUE THREAD

**Issue by NikolayRys** [NikolayRys/Likely#177]
- [ ] Logo
- [x] Comments: https://github.com/NikolayRys/Likely/pull/162/files

**Comment by vitkarpov** [comment]
What's up the logo?

**Comment by NikolayRys** [comment]
Oh, not much, this is more a note for myself.

The current logo was sort-of a draft, I have a proper one now that I'll put into the repo.

**Comment by NikolayRys** [comment]
Document how to update counters on existing widget:
`likely.initiate({forceUpdate:true});`
