### ISSUE TITLE
Pocket sharing button

### ISSUE THREAD

**Issue by dzhlobo** [NikolayRys/Likely#18]
I'd like to implement Pocket button. Can you please give me any suggestions on how to get `countUrl` and `popupUrl`? Where to begin?

Official page: https://getpocket.com/publisher/button.

**Comment by iamakulov** [comment]
@Proghat, sorry for being so silent, I still haven’t got the time to figure out how to start working on the button. We’re going to release the button in 2.2 so I’ll definitely return to this sooner than later.

**Comment by mihdan** [comment]
Иван, а не проще дать АПИ для добавления своих кнопок, это было бы просто очень удобно

**Comment by NikolayRys** [comment]
Документация добавлена: https://github.com/NikolayRys/Likely#custom-button
