### ISSUE TITLE
Uncaught TypeError: o.promises[t] is not a function

### ISSUE THREAD

**Issue by likerRr** [NikolayRys/Likely#185]
Found this error in console on my site along with likelys' [home page](https://ilyabirman.net/projects/likely/)

**Comment by NikolayRys** [comment]
@likerRr Thanks for report.
However, likely's homepage still uses the previous version - 2.4. Could you please first make sure  that you updated it to the most recent one - 2.5? 
https://www.npmjs.com/package/ilyabirman-likely/v/2.5.0

**Comment by likerRr** [comment]
Unfortunately it still presents in `2.5.0` too

**Comment by NikolayRys** [comment]
Thanks, is it possible to share your page then? It would help us with reproducing it.

**Comment by likerRr** [comment]
What do you mean? I don't have all the accounts, but when I click any of the social button, I got vendor's modal window opened, so it seams working.

![image](https://user-images.githubusercontent.com/1290558/83021863-5058e200-a033-11ea-8b58-29f64ef41a39.png)

I think the issue is with counters, but I don't show them on my site.

**Comment by NikolayRys** [comment]
Indeed this line relates to the displayed number.

You said that "Found this error in console on my site", so I hoped to see your site to probably find out more about conditions when it happens because it doesn't happen every time.

**Comment by likerRr** [comment]
You can check out it [here](https://bus.av.by/zhong-tong/lck/16653959). Will it help?

**Comment by NikolayRys** [comment]
Thanks, but not a lot, it's still 2.4 as on the Likely webpage, which is significantly different from 2.5, I was hoping to see it happening with the last version.
It's better than nothing but might happen because of different reasons/require a different solution than 2.4.

**Comment by likerRr** [comment]
You are right, the version in prod is out of date. I tried the updated one on my local machine. For now I can't deploy it

**Comment by NikolayRys** [comment]
Gotcha, I look into it using the current examples but post the link here please when you have deployed it.

**Comment by likerRr** [comment]
@NikolayRys hello! We deployed the app with updated likely lib and error has gone. You can check it [here](https://bus.av.by/mercedes-benz/sprinter/100001204)

**Comment by NikolayRys** [comment]
@likerRr Perfect, thanks for the feedback, that probably explains why I haven't succeeded in reproducing it myself. 
I'll leave the issue open for a while if anybody experiences it too and can show it.

**Comment by NikolayRys** [comment]
I guess, we don't need this one anymore
