### ISSUE TITLE
Plans for 2.6

### ISSUE THREAD

**Issue by NikolayRys** [NikolayRys/Likely#186]
Another small release before 3.0:

- [x] Update icons to modern ones: https://github.com/NikolayRys/Likely/issues/187
- [x] Expanded twitter params with "hashtags"
- [x] Remove multiple deprecation warnings if the is more than one set of buttons
- [x] Update licence
- [x] Add specific files into npm publish config. ` "files": ["release",` is too generic, so unrelated files get into it
- [x] Add linting for Stylus files

**Comment by farhodjon** [comment]
@NikolayRys could you please explain how to generate `svgIconPath` from a regular SVG file? I use this on my website and would like to add some additional icons but couldn't understand how to make an SVG icon path. Thanks.

**Comment by NikolayRys** [comment]
@farhodjon thank you for this question, but it would be better to create a new issue to ask this.
You just need to remove the initial `M` and the final `z` from the SVG string for it to be functional as svgIconPath.

We have plans to make it simpler in 3.0 and accept there regular svgs, but it is a breaking change.

**Comment by NikolayRys** [comment]
Now handled in https://github.com/NikolayRys/Likely/pull/195
