### ISSUE TITLE
twitter data-title issue

### ISSUE THREAD

**Issue by kvorobyov** [NikolayRys/Likely#188]
When **data-title** option is used with twitter button, two duplicate strings appear in the result tweet.

`<div class="twitter" data-title="ABC">Tweet</div>
`

**Tweet:**
ABC
ABC:
link

**Comment by NikolayRys** [comment]
Thank you for the feedback, I'll take a look. 
Quick question though, what version do you use?

**Comment by kvorobyov** [comment]
Thanks for a quick response.
I'm using 2.5.0, but this issue happened on version prior to it, I guess it was 2.4.

**Comment by NikolayRys** [comment]
Please install 2.6, it has been fixed there:
https://github.com/NikolayRys/Likely/releases/tag/v2.6
or
https://www.npmjs.com/package/ilyabirman-likely/v/2.6.0
