### ISSUE TITLE
Text duplication on twitter share

### ISSUE THREAD

**Issue by amshkv** [NikolayRys/Likely#192]
Hi.
If I add code like this to the site:
`<div class="twitter" data-title="new title" data-url="https://google.com"></div>`
then I get duplicate title and links in the sharing window:
![image](https://user-images.githubusercontent.com/23584933/93227029-a2597b00-f77c-11ea-9017-cc9af2f56208.png)

If I change the title or link in DOM, I get two different titles/links - the old one that was on page load and the new one that I added
![image](https://user-images.githubusercontent.com/23584933/93227351-ee0c2480-f77c-11ea-9a43-ca5b38c0833a.png)

thx

**Comment by amshkv** [comment]
Oh, sorry, its double https://github.com/NikolayRys/Likely/issues/188

**Comment by NikolayRys** [comment]
No probs, it's on our radar 👍
