### ISSUE TITLE
Problem with whatsapp

### ISSUE THREAD

**Issue by kosh89** [NikolayRys/Likely#200]
Trying to share link via whatsapp, but nothing happen. 
Its ok if you have an installed app. But you can't share via web app.

**Comment by NikolayRys** [comment]
Please provide a link to the webapp that you are referring to, there are several of them

**Comment by NikolayRys** [comment]
@kosh89 Fixed in 3.0, please update your version: https://github.com/NikolayRys/Likely/releases/tag/v3.0.0
