### ISSUE TITLE
data-url param adds dup url

### ISSUE THREAD

**Issue by kvorobyov** [NikolayRys/Likely#201]
There seems to be a bug since the 2.6 release.
When using the data-url parameter the link is added twice, this can be noticed on Twitter, other services seem to ignore it.
`https://twitter.com/intent/tweet?url=http%3A%2F%2Fwww.domain.com&text=Title&url=http%3A%2F%2Fwww.domain.com&via=MyTwitter`
<img width="603" alt="image" src="https://user-images.githubusercontent.com/7858049/216760857-c3510270-4972-41fb-b5e2-554278514855.png">

**Comment by NikolayRys** [comment]
Thanks for report, the fix will be in the next release

**Comment by NikolayRys** [comment]
@kvorobyov Fixed in 3.0, please update: https://github.com/NikolayRys/Likely/releases/tag/v3.0.0
