### ISSUE TITLE
share button works only one time in share modal

### ISSUE THREAD

**Issue by kenzo08** [NikolayRys/Likely#202]
in builded mode if I reopen share modal,  all share buttons doesn't work.   in localhost mode no problem. But in builded app I cannot press share button second time. In console there are no errors. just nothing.  

builder vite. framework nuxt 3

**Comment by NikolayRys** [comment]
Sorry, there is not enough info for reproducing it. ATM, we don't have native Vue support, it may work, or may not. 
If you are willing to submit a reproducible example, maybe we can take it from there.

**Comment by NikolayRys** [comment]
Closing due no feedback
