### ISSUE TITLE
Homepage: Update Likely to 3.0

### ISSUE THREAD

**Issue by Ronef** [NikolayRys/Likely#203]
As [i see](https://ilyabirman.net/css/core/core.js.css), Likely 2.8 is used for now.

Additionally, [README → Get → CDN](https://github.com/NikolayRys/Likely/blob/master/README.md#get) also refers to 2.x.

**Comment by NikolayRys** [comment]
This will be amended in the coming days;
there is a minor bug with style inheritance that we would like to fix first.

**Comment by NikolayRys** [comment]
Done
