### ISSUE TITLE
Use flexbox with gap instead of margins

### ISSUE THREAD

**Issue by Ronef** [NikolayRys/Likely#204]
For now each icon has own margins for each size + parent container has related negative margins.

It can be replaced by modern `display: inline-flex;` and `gap`, which is more convenient and powerful.

For example, column orientation #72 will be implemented in this case by just one rule: `flex-direction: column;`.

**Comment by NikolayRys** [comment]
Do you want to make a PR?

**Comment by Ronef** [comment]
https://github.com/NikolayRys/Likely/pull/205
