### ISSUE TITLE
Will a new twitter logo be added?

### ISSUE THREAD

**Issue by kzgzhn** [NikolayRys/Likely#207]
Hello. Are there any plans to add a new Twitter logo? 
It would be great to know if this is being considered. 
Thank you for your response.

**Comment by NikolayRys** [comment]
Hi, yes, it is, we will add it as a separate service in the next release sometime later this month, without removing existing twitter

**Comment by NikolayRys** [comment]
X.com added as a service in version 3.2: 
https://github.com/NikolayRys/Likely/releases/tag/v3.2.0
