### ISSUE TITLE
Telegram share

### ISSUE THREAD

**Issue by nojqva** [NikolayRys/Likely#208]
Привет. Ни как не могу понять, как сделать так, чтобы при "поделиться" в телегу был сначала текст, а потом шла ссылка, а не наоборот.

**Comment by NikolayRys** [comment]
Это достаточно сложно сделать элегантно, так как сам API метод Телеграма принимает отдельными параметрами ссылку и описание к ней: https://core.telegram.org/widgets/share

Но это можно обойти, если все, включая перенос строки, указать как урл, а title обнулить: 
` <div class="telegram" data-url="Hello%0Ahttps%3A%2F%2Fgoogle.com" data-title=" ">Send</div>`
Получится вот так:
![image](https://github.com/user-attachments/assets/6f730843-0df0-4b8d-acb4-047ef75b2c0d)
