### ISSUE TITLE
List of breaking changes for Likely 3

### ISSUE THREAD

**Issue by iamakulov** [NikolayRys/Likely#76]
Likely 3 should include some major feature additions, and we want to bind several breaking changes to this release. There’s neither a concrete date nor a concrete list of features for this version.
- [ ] Bundle both JS and CSS into one file. This will let us get rid of Gulp and switch to Webpack completely.
- [ ] Remove `likely.initate()` which is an alias for `likely.initiate()` and was originally introduced by a mistake.
- [ ] Remove `likely()` in favor of `likely.initiate()` (see https://github.com/ilyabirman/Likely/issues/82#issuecomment-238572834).
- [ ] Join `.likely_visible` and `.likely_ready` into a single class: it’s unclear why they are ever separate. (This could probably be a large breaking change because people can rely on one of these classes.)
- [ ] Make Likely auto-initialize when being used as a CommonJS module.

The list will most likely be expanded in the future.

**Comment by vitkarpov** [comment]
> Bundle both JS and CSS into one file

What does it mean exactly? I didn't get it right, i think.

**Comment by iamakulov** [comment]
> What does it mean exactly? 

I think of doing `require('../styles/likely.styl')` in `index.js` (with `'style?insertAt=top!css!stylus` loader). Webpack will load `likely.styl`, compile it into CSS and bundle it together with the JS code into `release/likely.js`. Then, Webpack will automatically add the styles to `<head>` when `likely.js` is loaded in the browser. (`insertAt=top` is required to make the user styles have more priority than ours.)

Have I explained OK or is something unclear?

**Comment by iamakulov** [comment]
BTW, I don’t yet know if this behavior is OK for users that use Likely in SPAs. I’ll try collecting more data when we get nearer to 3.0.

**Comment by vitkarpov** [comment]
Yep, this seems okay. Thank you.

It completely changes the way Likely's being added to the page, and I think about flashes of unstyled content.

Correct me if I'm wrong.

Browser gets button in html:

```html
<div class="likely">
    <div class="facebook">Share</div>
    <div class="twitter">Tweet</div>
    <div class="gplus">+1</div>
    <div class="vkontakte">Share</div>
    <div class="pinterest">Pin</div>
    <div class="odnoklassniki">Like</div>
    <div class="telegram">Send</div>
</div>
```

In the previous scheme we had css loaded in the head section, and to the moment browser parsed this html, all styles were ready to be applied to it.

Now we have a script which adds styles dynamically to the head, and usually scripts are in the end of the page, so at this moment we have no styles for button, right?

**Comment by iamakulov** [comment]
> I think about flashes of unstyled content

Hm, good point, haven’t thought of it. I’ll discuss this with @ilyabirman later, probably we won’t do bundling.

**Comment by iamakulov** [comment]
> I think about flashes of unstyled content

Or probably there won’t be: as far as I remember, the browser don’t display anything untill all the HTML is parsed and all the scripts are executed, so if we add styles synchronously, we won’t experience anything. (Should be tested though.)

**Comment by iamakulov** [comment]
Added a new point following a discussion with @ilyabirman:

> - [ ] Make Likely auto-initialize when being used as a CommonJS module.

**Comment by vitkarpov** [comment]
> Make Likely auto-initialize when being used as a CommonJS module.

Could this be optional? (on by default, if you will). I think SPA developers may want to init buttons in custom moment of time (because of complex app init)

**Comment by vitkarpov** [comment]
> Bundle both JS and CSS into one file.

Also, I think I got the main idea of @ilyabirman — it should be less interface as possible: instead of 2 files it should be one, instead of handy initiate it should be auto and etc.

I totally agree with it! As developers we face challenges (such as FOUC) and have to tackle it instead of doing everything the same as before.

**Comment by iamakulov** [comment]
> Could this be optional? (on by default, if you will). I think SPA developers may want to start up buttons in custom moment of time (because of complex app init)

Yeah, `likely.initiate()` is still there, it’s just that it’ll be automatically called when importing the package.

**Comment by NikolayRys** [comment]
Closed in favor of https://github.com/NikolayRys/Likely/issues/163
