### ISSUE TITLE
Facebook counter catches the “Application request limit reached” error

### ISSUE THREAD

**Issue by iamakulov** [NikolayRys/Likely#88]
**Steps to reproduce:**
1. Go to [Tinkoff Journal](http://journal.tinkoff.ru/), wait until the page is loaded.
2. Open the console, refresh the page.
3. Check a Facebook counter request (filter by `?id=`) in the network tab.

**Expected result:**
The request returns a JSONP response with the share count.

**Actual result:**
The request returns a JSONP response with an error:

``` json
{
   "error": {
      "message": "(#4) Application request limit reached",
      "type": "OAuthException",
      "is_transient": true,
      "code": 4,
      "fbtrace_id": "Ap5Jr2xVCxj"
   }
}
```

---

Looks like this is caused by a lot of Likely buttons each doing a request to the API (e. g. 101 requests total on the Tinkoff Journal’s main page). 

Possible solutions:
- find another, less limited API method for getting the counter,
- find a way to increase the limit for this API method (by providing a token probably?)
- detect multiple Likely instances on the page and do a single `?ids=<url1>,<url2>,...` request instead of multiple `?id=<url>` ones (this way is pretty hard).

**Comment by vitkarpov** [comment]
@iamakulov Do we have API token here?

**Comment by iamakulov** [comment]
No, it should be registered.

**Comment by vitkarpov** [comment]
Okay. I guess, we should get back to this after Ilya will have a key

**Comment by iamakulov** [comment]
Have you contacted him, or should I do this?

**Comment by vitkarpov** [comment]
Nope, I haven't :)

**Comment by iamakulov** [comment]
Sure, I’ll rich him soon.

**Comment by NikolayRys** [comment]
Not relevant anymore
